title: Pulsebook
description: Development practices, workflows, and technical architecture guide for Equevu
logo: /Equevu.svg
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
github:
  is_project_page: false
url: "https://equevu.github.io/Pulsebook/"
